create database COURSE_G6;
use COURSE_G6;

create table COURSE (
COURSE_ID INT primary key auto_increment ,
COURSE_NAME VARCHAR(30) NOT NULL unique,
COURSE_PRICE INT NOT NULL,
EMP_ID  INT NOT NULL,
COURSE_TIME TIMESTAMP NOT NULL,
COURSE_CONTENT VARCHAR(300) NOT NULL,
COURSE_STATUS BOOLEAN NOT NULL,
COURSE_VIDEO  INT,
RATE_NUM INT,
RATE_STAR INT
-- foreign key(EMP_ID) references EMP(EMP_ID)
);

create table STUDENT_COMMENT (
STUDENT_COMMENT_ID INT primary key auto_increment ,
COURSE_ID INT NOT NULL ,
MEM_ID INT NOT NULL,
STUDENT_COMMENT_CONTENT VARCHAR(300),
STUDENT_COMMENT_DATE DATETIME,
EMP_ID INT,
CHEF_COMMENT_CONTNENT VARCHAR(300)
-- foreign key(COURSE_ID) references COURSE(COURSE_ID)
-- foreign key(MEM_ID) references MEMBERS(MEM_ID)
-- foreign key(EMP_ID) references EMP(EMP_ID)
);

create table COURSE_IMG (
COURSE_IMG_ID INT primary key auto_increment,
COURSE_IMG LONGBLOB,
COURSE_ID INT NOT NULL
-- foreign key(COURSE_ID) references COURSE(COURSE_ID)
);