create schema GROUPORDER_G6;
use GROUPORDER_G6;

create table GROUP_ORDER_DETAIL(
GROUP_ORDER_ID INT,
MEM_ID INT,
-- foreign key(GROUP_ORDER_ID) references GROUP_ORDER_MASTER(GROUP_ORDER_ID);
-- foreign key(MEM_ID) references MEMBERS(MEM_ID);
primary key (GROUP_ORDER_ID,MEM_ID),
GROUP_ORDER_AMOUNT INT not null,
ADDRESS varchar(100) not null,
GROUP_PRODUCT_PAYING TINYINT not null,
GROUP_PRODUCT_STATUS TINYINT not null default'0',
GROUP_PRODUCT_OTHERS VARCHAR(150),
RECEIVER_NAME VARCHAR(50)not null,
RECEIVER_ADDRESS VARCHAR(100) not null,
RECEIVER_PHONE VARCHAR(10)not null,
GROUP_PRODUCT_PRICE INT not null );



select* from GROUP_ORDER_DETAIL;


create table GROUP_ORDER_MASTER(
GROUP_ORDER_ID INT primary key not null,
MEM_ID INT,
GROUP_PRODUCT_ID INT,
-- foreign key(MEM_ID) reference MEMBERS(MEM_ID);
-- foreign key(GROUP_PRODUCT_ID) reference GROUP_PRODUCT(GROUP_PRODUCT_ID);
NUMBER_OF_PRODUCT INT not null,
GROUP_ORDER_STATUS TINYINT default'0',
GROUP_ORDER_BONUS INT,
TOTAL_GROUP_PRODUCT_PRICE INT);

select* from GROUP_ORDER_MASTER;



create table GROUP_PRODUCT(
GROUP_PRODUCT_ID INT primary key not null ,
GROUP_ACTIVITY_ID INT,
-- foreign key(GROUP_ACTIVITY_ID) reference GROUP(GROUP_ACTIVITY_ID);
GROUP_PRODUCT_NAME VARCHAR(40) not null,
GROUP_PRODUCT_CONTENT VARCHAR(300) not null,
GROUP_PRODUCT_PRICE INT not null,
GROUP_PRODUCT_STARDATE DATE not null,
GROUP_PRODUCT_TIMEGROUP_PRODUCT_ENDDATE  DATE not null,
GROUP_PRODUCT_STATUS BOOLEAN not null);
select* from GROUP_PRODUCT;

create table GROUP_ACTIVITY (
GROUP_ACTIVITY_ID INT primary key not null,
GROUP_PRODUCT_NAME VARCHAR(50)not null,
GROUP_ACTIVITY_CONTENT VARCHAR(300)not null,
GROUP_ORDER_STAR DATETIME not null,
GROUP_ORDER_END DATETIME not null,
GROUP_ORDER_MIN INT not null,
GROUP_NAME VARCHAR(40) ,
GROUP_ORDER_DISCOUNT DECIMAL(3,2)
);

select*from GROUP_ACTIVITY;

create table GROUP_PRODUCT_IMG(
GROUP_PRODUCT_IMG_ID INT primary key not null,
GROUP_PRODUCT_ID INT,
-- foreign key(GROUP_PRODUCT_ID) reference GROUP_PRODUCT(GROUP_PRODUCT_ID); 
GOURP_PRODUCT_IMG LONGBLOB
);

select*from GROUP_PRODUCT_IMG;